[project]
name = "workspace"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "delta-spark>=3.3.0",
    "polars>=1.26.0",
    "pyspark>=3.5.5",
]
